export enum EBookStatus {
  PENDING = "PENDING",
  WAITINGPAYMENT = "WAITINGPAYMENT",
  APPROVED = "APPROVED",
  OCCURRING = "OCCURRING",
  REJECTED = "REJECTED",
  CANCELED = "CANCELED",
  FINISHED = "FINISHED",
}
