export enum EPERMISSIONS {
  "CREATE_USER" = "CREATE_USER",
  "DELETE_USER" = "DELETE_USER",
  "RESET_USER_PASSWORD" = "RESET_USER_PASSWORD",
  "APPROVE_MENTOR_FEE" = "APPROVE_MENTOR_FEE",
  "APPROVE_LIVETRAINING_FEE" = "APPROVE_LIVETRAINING_FEE",
  "APPROVE_MENTOR" = "APPROVE_MENTOR",
  "PROGRESS_WD" = "PROGRESS_WD",
  "REJECT_WD" = "REJECT_WD",
  "FINISH_WD" = "FINISH_WD",
}
