export enum EROLES {
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
  PARTICIPANT = "PARTICIPANT",
  MENTOR = "MENTOR",
  ORGANISATION = "ORGANISATION",
  PAYMENTGATEWAY = "PAYMENTGATEWAY",
}
